### ISSUE TITLE
add module checks to patchers

### ISSUE THREAD

**Issue by SeeSharpCode** [SeeSharpCode/zEdit-patchus-maximus#14]
Some record edits should be module-dependent, e.g. only patch weapons if the warrior module is installed.

For the alpha release, I'm assuming all modules are used.

**Comment by matortheeternal** [comment]
So we need a way to detect if a module is installed.  Is that just an ESP presence check?  If so, then we can just check for ESP presence in the patcher's `initialize` function and store the states as booleans in `locals`.

Something like:

```js
const detectPerMaModules = function(locals) {
  xelib.GetLoadedFileNames().forEach(filename => {
    let match = filename.match(/PerkusMaximus_(?!Master)(\w+)\.esp/);
    if (match) locals[`use${match[1]}`] = true;
  });
};

// ... (in initialize)
detectPerMaModules(locals);
// ...
```

**Comment by matortheeternal** [comment]
Added in e036226

**Comment by matortheeternal** [comment]
cobjPatcher now uses detected modules as of d1753ac

**Comment by SeeSharpCode** [comment]
The SkyProc used XML settings to determine which modules were installed. Not sure why since the installed ESPs are a much better indicator. I'll roll with this method.

**Comment by Muthera** [comment]
Muthsera SeeSharpCode how be installed this patch? Sorry but i'm full noob in programming and usally user of PaMa,

**Comment by matortheeternal** [comment]
@Muthera still being developed.  wait for first release!
